project:
  type: website
  output-dir: _site

website:
  title: "Ndu Ugwuanyi"
  search: false
  navbar:
    title: false
    pinned: true
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: job-market-paper.qmd
        text: Job Market Paper
      - href: big-agenda.qmd
        text: Research Agenda
      - href: teaching.qmd
        text: Teaching
      # - href: writing.qmd
      #   text: Writing
      - href: cv.qmd
        text: CV
      - href: contact.qmd
        text: Contact
    tools:
    - icon: linkedin
      href: "https://www.linkedin.com/in/rndu/"
      aria-label: LinkedIn

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    anchor-sections: false